### PR TITLE
json: Fix crash when parsing invalid input

### LINKED ISSUE #285: Crash when parsing invalid JSON
Satyr's JSON parser segfaults when trying to parse the simple input `]`.

The problem lies in https://github.com/abrt/satyr/blob/ba0dc050df7803cf119c28f9db6963a9a1aeee4e/lib/json.c#L359 where `top` is dereferenced before being assigned a meaningful value.

Discovered with the help of [american fuzzy lop](http://lcamtuf.coredump.cx/afl/).

### PR DESCRIPTION
**Pull request by mgrabovsky**
Fixes #285

### CODE REVIEW

File: lib/json.c [hunk 1]
```diff
@@ -485,7 +485,7 @@ sr_json_parse_ex(struct sr_json_settings *settings,
                         continue;
 
                     case '"':
-                        if (flags & flag_need_comma && (!state.settings.settings & SR_JSON_RELAXED_COMMAS))
+                        if (flags & flag_need_comma && !(state.settings.settings & SR_JSON_RELAXED_COMMAS))
```
Comment (ernestask) [inline lib/json.c]: The commit message doesn’t mention anything about commas.

**Comment by ernestask** [comment]
Can you also add the reference to the issue to the commit message?

File: lib/json.c (hunk 1 above)
Comment (mgrabovsky) [reply lib/json.c]: This was just an unrelated detail pointed out by Clang. The `!` does not do what seems to have been intended and either a `~` should have been used instead or this parenthesization used.

I have removed this change, since it doesn't really matter if we only have one possible flag.

Comment (ernestask) [reply lib/json.c]: I mean, if it’s correct, it’s fine to make that change, just in a separate commit.

**Comment by ernestask** [comment]
Anyway, I’m going to merge this now, since I’m sort of blocked.

File: lib/json.c [hunk 2]
```diff
@@ -356,9 +356,9 @@ sr_json_parse_ex(struct sr_json_settings *settings,
                     continue;
 
                 case ']':
-                    if (top->type == SR_JSON_ARRAY)
+                    if (top && top->type == SR_JSON_ARRAY)
                         flags = (flags & ~ (flag_need_comma | flag_seek_value)) | flag_next;
-                    else if (!state.settings.settings & SR_JSON_RELAXED_COMMAS)
+                    else if (!top || !(state.settings.settings & SR_JSON_RELAXED_COMMAS))
```
Comment (ernestask) [inline lib/json.c]: There’s still a change in the settings logic.

Comment (mgrabovsky) [reply lib/json.c]: Yikes, removed.
